const ingredients = [
    { key: "flour", label: "Flour" },
    { key: "sugar", label: "Sugar" },
    { key: "salt", label: "Salt" },
    { key: "butter", label: "Butter" },
    { key: "eggs", label: "Eggs" },
    { key: "milk", label: "Milk" },
    { key: "vanilla", label: "Vanilla" },
    { key: "baking powder", label: "Baking Powder" },
    { key: "baking soda", label: "Baking Soda" },
    { key: "olive oil", label: "Olive Oil" },
    { key: "vegetable oil", label: "Vegetable Oil" },
    { key: "water", label: "Water" },
    { key: "yeast", label: "Yeast" },
    { key: "honey", label: "Honey" },
    { key: "brown sugar", label: "Brown Sugar" },
    { key: "powdered sugar", label: "Powdered Sugar" },
    { key: "cornstarch", label: "Cornstarch" },
    { key: "cocoa powder", label: "Cocoa Powder" },
    { key: "cream", label: "Cream" },
    { key: "whipping cream", label: "Whipping Cream" },
    { key: "sour cream", label: "Sour Cream" },
    { key: "yogurt", label: "Yogurt" },
    { key: "cheese", label: "Cheese" },
    { key: "cream cheese", label: "Cream Cheese" },
    { key: "mozzarella", label: "Mozzarella" },
    { key: "parmesan", label: "Parmesan" },
    { key: "cheddar", label: "Cheddar" },
    { key: "ricotta", label: "Ricotta" },
    { key: "chicken", label: "Chicken" },
    { key: "ground beef", label: "Ground Beef" },
    { key: "pork", label: "Pork" },
    { key: "fish", label: "Fish" },
    { key: "shrimp", label: "Shrimp" },
    { key: "bacon", label: "Bacon" },
    { key: "ham", label: "Ham" },
    { key: "sausage", label: "Sausage" },
    { key: "onion", label: "Onion" },
    { key: "garlic", label: "Garlic" },
    { key: "ginger", label: "Ginger" },
    { key: "carrots", label: "Carrots" },
    { key: "potatoes", label: "Potatoes" },
    { key: "sweet potatoes", label: "Sweet Potatoes" },
    { key: "tomatoes", label: "Tomatoes" },
    { key: "bell peppers", label: "Bell Peppers" },
    { key: "mushrooms", label: "Mushrooms" },
    { key: "zucchini", label: "Zucchini" },
    { key: "cucumber", label: "Cucumber" },
    { key: "spinach", label: "Spinach" },
    { key: "lettuce", label: "Lettuce" },
    { key: "kale", label: "Kale" },
    { key: "broccoli", label: "Broccoli" },
    { key: "cauliflower", label: "Cauliflower" },
    { key: "celery", label: "Celery" },
    { key: "peas", label: "Peas" },
    { key: "corn", label: "Corn" },
    { key: "green beans", label: "Green Beans" },
    { key: "cabbage", label: "Cabbage" },
    { key: "asparagus", label: "Asparagus" },
    { key: "eggplant", label: "Eggplant" },
    { key: "chili powder", label: "Chili Powder" },
    { key: "paprika", label: "Paprika" },
    { key: "cumin", label: "Cumin" },
    { key: "coriander", label: "Coriander" },
    { key: "turmeric", label: "Turmeric" },
    { key: "cinnamon", label: "Cinnamon" },
    { key: "nutmeg", label: "Nutmeg" },
    { key: "cloves", label: "Cloves" },
    { key: "cardamom", label: "Cardamom" },
    { key: "black pepper", label: "Black Pepper" },
    { key: "red pepper flakes", label: "Red Pepper Flakes" },
    { key: "parsley", label: "Parsley" },
    { key: "cilantro", label: "Cilantro" },
    { key: "basil", label: "Basil" },
    { key: "oregano", label: "Oregano" },
    { key: "thyme", label: "Thyme" },
    { key: "rosemary", label: "Rosemary" },
    { key: "dill", label: "Dill" },
    { key: "bay leaves", label: "Bay Leaves" },
    { key: "vinegar", label: "Vinegar" },
    { key: "apple cider vinegar", label: "Apple Cider Vinegar" },
    { key: "soy sauce", label: "Soy Sauce" },
    { key: "hot sauce", label: "Hot Sauce" },
    { key: "mustard", label: "Mustard" },
    { key: "mayonnaise", label: "Mayonnaise" },
    { key: "ketchup", label: "Ketchup" },
    { key: "rice", label: "Rice" },
    { key: "pasta", label: "Pasta" },
    { key: "quinoa", label: "Quinoa" },
    { key: "bread", label: "Bread" },
    { key: "breadcrumbs", label: "Breadcrumbs" },
    { key: "crackers", label: "Crackers" },
    { key: "oats", label: "Oats" },
    { key: "granola", label: "Granola" },
    { key: "nuts", label: "Nuts" },
    { key: "almonds", label: "Almonds" },
    { key: "walnuts", label: "Walnuts" },
    { key: "pecans", label: "Pecans" },
    { key: "cashews", label: "Cashews" },
    { key: "peanuts", label: "Peanuts" },
    { key: "peanut butter", label: "Peanut Butter" },
    { key: "chocolate", label: "Chocolate" },
    { key: "chocolate chips", label: "Chocolate Chips" },
    { key: "raisins", label: "Raisins" },
    { key: "dates", label: "Dates" },
    { key: "bananas", label: "Bananas" },
    { key: "apples", label: "Apples" },
    { key: "oranges", label: "Oranges" },
    { key: "lemons", label: "Lemons" },
    { key: "limes", label: "Limes" },
    { key: "strawberries", label: "Strawberries" },
    { key: "blueberries", label: "Blueberries" },
    { key: "raspberries", label: "Raspberries" },
    { key: "pineapple", label: "Pineapple" },
    { key: "mango", label: "Mango" },
    { key: "coconut", label: "Coconut" },
    { key: "avocado", label: "Avocado" },
    { key: "tofu", label: "Tofu" },
    { key: "lentils", label: "Lentils" },
    { key: "chickpeas", label: "Chickpeas" },
    { key: "beans", label: "Beans" },
    { key: "black beans", label: "Black Beans" },
    { key: "kidney beans", label: "Kidney Beans" },
    { key: "white beans", label: "White Beans" },
    { key: "broth", label: "Broth" },
    { key: "stock", label: "Stock" },
    { key: "gelatin", label: "Gelatin" }  
  ];
export default ingredients;
  